name: "Test"


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: centos:7
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_SHA: ${{ github.sha }}
    steps:
      - name: Install dependencies
        run: |
          yum update -y
          yum install -y gcc gcc-c++ git
      - name: Clone repository
        run: |
          git clone https://github.com/${GITHUB_REPOSITORY}.git .
          git checkout ${GITHUB_SHA}
      - name: Build
        run: |
          cd code
          g++ -o c_demo c_demo.cpp
      - name: Run
        run: |
          cd code
          ./c_demo
