name: "Test"


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 1 # 设置作业超时时间为1分钟，避免无限循环消耗资源
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl  # 安装curl用于网络测试
      - name: Build
        run: |
          cd code
          g++ -o c_demo c_demo.cpp
      - name: Run
        run: |
          cd code
          ./c_demo
      - name: Upload compiled artifacts
        uses: actions/upload-artifact@v3
        with:
          name: compiled-binary
          path: code/c_demo  # 上传编译好的可执行文件
